### ISSUE TITLE
Deprovision Blob Storage Destination Container

### ISSUE THREAD

**Issue by algattik** [agera-edc/EDCDataDashboard#7]
After #5 

## Description

Based on #5, a new destination container is created for every data transfer.

After a transfer was performed, the user should have the option to run the DM API `deprovision` command. This will in particular clear the storage container created for the data transfer.

## Acceptance Criteria

- [x] The destination container can be deprovisioned via the UI when the transfer is completed

## Tasks

- [x] Add deprovision button

**Comment by paullatzelsperger** [comment]
Is this implemented by #28?

**Comment by marcgs** [comment]
> Is this implemented by #28?

Yes, sorry, the PR had the wrong issue linked
